language: python

python:
      - "2.7.9"

install:
        - pip install coveralls
        - python setup.py develop

script: 
        - python setup.py nosetests

after_success:
          coveralls
